#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef STOREKITWRAPPER_SWIFT_H
#define STOREKITWRAPPER_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="StoreKitWrapper",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="StoreKitWrapper",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_ENUM_FWD_DECL(NSInteger, StoreKitWrapperLogLevel)
@class NSString;
@class NSError;
SWIFT_PROTOCOL("_TtP15StoreKitWrapper22IStoreKitWrapperLogger_")
@protocol IStoreKitWrapperLogger
- (BOOL)isEnabledWithLogLevel:(enum StoreKitWrapperLogLevel)logLevel SWIFT_WARN_UNUSED_RESULT;
- (void)logWithLogLevel:(enum StoreKitWrapperLogLevel)logLevel eventId:(NSInteger)eventId eventName:(NSString * _Nullable)eventName message:(NSString * _Nonnull)message error:(NSError * _Nullable)error;
@end

@protocol StoreKitManagerDelegate;
SWIFT_CLASS("_TtC15StoreKitWrapper15StoreKitManager")
@interface StoreKitManager : NSObject
@property (nonatomic, strong) id <StoreKitManagerDelegate> _Nullable delegate;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithLogger:(id <IStoreKitWrapperLogger> _Nullable)logger delegate:(id <StoreKitManagerDelegate> _Nullable)delegate OBJC_DESIGNATED_INITIALIZER;
- (void)initialize;
- (void)shutdown;
- (void)getProductsWithProductIdentifiers:(NSArray<NSString *> * _Nonnull)productIdentifiers;
- (void)getCurrentEntitlements;
- (void)sync;
- (void)getUnfinishedTransactions;
- (void)purchaseWithProductIdentifier:(NSString * _Nonnull)productIdentifier;
- (void)purchaseWithProductIdentifier:(NSString * _Nonnull)productIdentifier appAccountToken:(NSString * _Nullable)appAccountToken;
- (void)purchaseWithProductIdentifier:(NSString * _Nonnull)productIdentifier appAccountToken:(NSString * _Nullable)appAccountToken quantity:(NSInteger)quantity;
- (void)finishTransactionWithTransactionIdentifier:(uint64_t)transactionIdentifier;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, StoreKitWrapperErrorCode)
@class StoreKitProduct;
@class StoreKitTransaction;
SWIFT_ENUM_FWD_DECL(NSInteger, StoreKitPurchaseResult)
SWIFT_PROTOCOL("_TtP15StoreKitWrapper23StoreKitManagerDelegate_")
@protocol StoreKitManagerDelegate
- (void)initializationCompletedWithErrorCode:(enum StoreKitWrapperErrorCode)errorCode errorMessage:(NSString * _Nullable)errorMessage;
- (void)shutdownCompletedWithErrorCode:(enum StoreKitWrapperErrorCode)errorCode errorMessage:(NSString * _Nullable)errorMessage;
- (void)availableProductsCompletedWithResult:(NSArray<StoreKitProduct *> * _Nonnull)withResult errorCode:(enum StoreKitWrapperErrorCode)errorCode errorMessage:(NSString * _Nullable)errorMessage;
- (void)currentEntitlementsCompletedWithResult:(NSArray<StoreKitTransaction *> * _Nonnull)withResult errorCode:(enum StoreKitWrapperErrorCode)errorCode errorMessage:(NSString * _Nullable)errorMessage;
- (void)appStoreSyncCompletedWithErrorCode:(enum StoreKitWrapperErrorCode)errorCode errorMessage:(NSString * _Nullable)errorMessage;
- (void)unfinishedTransactionsCompletedWithResult:(NSArray<StoreKitTransaction *> * _Nonnull)withResult errorCode:(enum StoreKitWrapperErrorCode)errorCode errorMessage:(NSString * _Nullable)errorMessage;
- (void)purchaseCompletedWithResult:(StoreKitTransaction * _Nullable)withResult purchaseResult:(enum StoreKitPurchaseResult)purchaseResult errorCode:(enum StoreKitWrapperErrorCode)errorCode errorMessage:(NSString * _Nullable)errorMessage;
- (void)finishTransactionCompletedWithTransactionIdentifier:(uint64_t)transactionIdentifier errorCode:(enum StoreKitWrapperErrorCode)errorCode errorMessage:(NSString * _Nullable)errorMessage;
- (void)transactionUpdatedWithResult:(StoreKitTransaction * _Nonnull)withResult errorCode:(enum StoreKitWrapperErrorCode)errorCode errorMessage:(NSString * _Nullable)errorMessage;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, StoreKitProductType)
@class NSDecimalNumber;
@class StoreKitSubscriptionInfo;
SWIFT_CLASS("_TtC15StoreKitWrapper15StoreKitProduct")
@interface StoreKitProduct : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
@property (nonatomic, readonly) enum StoreKitProductType productType;
@property (nonatomic, readonly, copy) NSString * _Nonnull productTypeDisplayName;
@property (nonatomic, readonly, copy) NSString * _Nonnull displayName;
@property (nonatomic, readonly, copy) NSString * _Nonnull displayDescription;
@property (nonatomic, readonly, copy) NSString * _Nonnull displayPrice;
@property (nonatomic, readonly, strong) NSDecimalNumber * _Nonnull price;
@property (nonatomic, readonly, copy) NSString * _Nonnull currencyCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull localeIdentifier;
@property (nonatomic, readonly) BOOL isFamilyShareable;
@property (nonatomic, readonly, strong) StoreKitSubscriptionInfo * _Nullable subscriptionInfo;
@property (nonatomic, readonly, copy) NSString * _Nonnull jsonRepresentation;
- (nonnull instancetype)initWithIdentifier:(NSString * _Nonnull)identifier productType:(enum StoreKitProductType)productType productTypeDisplayName:(NSString * _Nonnull)productTypeDisplayName displayName:(NSString * _Nonnull)displayName displayDescription:(NSString * _Nonnull)displayDescription displayPrice:(NSString * _Nonnull)displayPrice price:(NSDecimalNumber * _Nonnull)price currencyCode:(NSString * _Nonnull)currencyCode localeIdentifier:(NSString * _Nonnull)localeIdentifier isFamilyShareable:(BOOL)isFamilyShareable subscriptionInfo:(StoreKitSubscriptionInfo * _Nullable)subscriptionInfo jsonRepresentation:(NSString * _Nonnull)jsonRepresentation OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, StoreKitProductType, open) {
  StoreKitProductTypeUnknown = -1,
  StoreKitProductTypeConsumable = 0,
  StoreKitProductTypeNonConsumable = 1,
  StoreKitProductTypeNonRenewableSubscription = 2,
  StoreKitProductTypeAutoRenewableSubscription = 3,
};

@class NSCoder;
@class NSBundle;
SWIFT_CLASS("_TtC15StoreKitWrapper29StoreKitProductViewController") SWIFT_AVAILABILITY(ios,introduced=17.0)
@interface StoreKitProductViewController : UIViewController
@property (nonatomic, readonly, copy) NSString * _Nonnull productIdentifier;
- (nonnull instancetype)initWithProductIdentifier:(NSString * _Nonnull)productIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC15StoreKitWrapper30StoreKitProductsViewController") SWIFT_AVAILABILITY(ios,introduced=17.0)
@interface StoreKitProductsViewController : UIViewController
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull productIdentifiers;
- (nonnull instancetype)initWithProductIdentifiers:(NSArray<NSString *> * _Nonnull)productIdentifiers OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, StoreKitPurchaseResult, open) {
  StoreKitPurchaseResultUnknown = -1,
  StoreKitPurchaseResultSucceeded = 0,
  StoreKitPurchaseResultPending = 1,
  StoreKitPurchaseResultCancelled = 2,
  StoreKitPurchaseResultFailed = 3,
};

@class StoreKitSubscriptionPeriod;
@class StoreKitSubscriptionOffer;
SWIFT_CLASS("_TtC15StoreKitWrapper24StoreKitSubscriptionInfo")
@interface StoreKitSubscriptionInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull subscriptionGroupIdentifier;
@property (nonatomic, readonly, copy) NSString * _Nullable groupDisplayName;
@property (nonatomic, readonly, strong) StoreKitSubscriptionPeriod * _Nonnull subscriptionPeriod;
@property (nonatomic, readonly) BOOL isEligibleForIntroductoryOffer;
@property (nonatomic, readonly, strong) StoreKitSubscriptionOffer * _Nullable introductoryOffer;
@property (nonatomic, readonly, copy) NSArray<StoreKitSubscriptionOffer *> * _Nonnull promotionalOffers;
@property (nonatomic, readonly, copy) NSArray<StoreKitSubscriptionOffer *> * _Nonnull winBackOffers;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, StoreKitSubscriptionOfferType)
SWIFT_ENUM_FWD_DECL(NSInteger, StoreKitSubscriptionOfferPaymentMode)
SWIFT_CLASS("_TtC15StoreKitWrapper25StoreKitSubscriptionOffer")
@interface StoreKitSubscriptionOffer : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable identifier;
@property (nonatomic, readonly) enum StoreKitSubscriptionOfferType offerType;
@property (nonatomic, readonly, copy) NSString * _Nonnull offerTypeDisplayName;
@property (nonatomic, readonly, copy) NSString * _Nonnull displayPrice;
@property (nonatomic, readonly, strong) NSDecimalNumber * _Nonnull price;
@property (nonatomic, readonly, copy) NSString * _Nonnull currencyCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull localeIdentifier;
@property (nonatomic, readonly) enum StoreKitSubscriptionOfferPaymentMode paymentMode;
@property (nonatomic, readonly, copy) NSString * _Nonnull paymentModeDisplayName;
@property (nonatomic, readonly, strong) StoreKitSubscriptionPeriod * _Nonnull period;
@property (nonatomic, readonly) NSInteger periodCount;
- (nonnull instancetype)initWithIdentifier:(NSString * _Nullable)identifier offerType:(enum StoreKitSubscriptionOfferType)offerType offerTypeDisplayName:(NSString * _Nonnull)offerTypeDisplayName displayPrice:(NSString * _Nonnull)displayPrice price:(NSDecimalNumber * _Nonnull)price currencyCode:(NSString * _Nonnull)currencyCode localeIdentifier:(NSString * _Nonnull)localeIdentifier paymentMode:(enum StoreKitSubscriptionOfferPaymentMode)paymentMode paymentModeDisplayName:(NSString * _Nonnull)paymentModeDisplayName period:(StoreKitSubscriptionPeriod * _Nonnull)period periodCount:(NSInteger)periodCount OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, StoreKitSubscriptionOfferPaymentMode, open) {
  StoreKitSubscriptionOfferPaymentModeUnknown = -1,
  StoreKitSubscriptionOfferPaymentModeFreeTrial = 0,
  StoreKitSubscriptionOfferPaymentModePayAsYouGo = 1,
  StoreKitSubscriptionOfferPaymentModePayUpFront = 2,
};

typedef SWIFT_ENUM(NSInteger, StoreKitSubscriptionOfferType, open) {
  StoreKitSubscriptionOfferTypeUnknown = -1,
  StoreKitSubscriptionOfferTypeIntroductory = 0,
  StoreKitSubscriptionOfferTypePromotional = 1,
  StoreKitSubscriptionOfferTypeWinBack = 2,
};

SWIFT_ENUM_FWD_DECL(NSInteger, StoreKitSubscriptionPeriodUnit)
SWIFT_CLASS("_TtC15StoreKitWrapper26StoreKitSubscriptionPeriod")
@interface StoreKitSubscriptionPeriod : NSObject
@property (nonatomic, readonly) NSInteger value;
@property (nonatomic, readonly) enum StoreKitSubscriptionPeriodUnit unit;
@property (nonatomic, readonly, copy) NSString * _Nonnull unitDisplayName;
- (nonnull instancetype)initWithValue:(NSInteger)value unit:(enum StoreKitSubscriptionPeriodUnit)unit unitDisplayName:(NSString * _Nonnull)unitDisplayName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, StoreKitSubscriptionPeriodUnit, open) {
  StoreKitSubscriptionPeriodUnitUnknown = -1,
  StoreKitSubscriptionPeriodUnitDay = 0,
  StoreKitSubscriptionPeriodUnitWeek = 1,
  StoreKitSubscriptionPeriodUnitMonth = 2,
  StoreKitSubscriptionPeriodUnitYear = 3,
};

SWIFT_CLASS("_TtC15StoreKitWrapper35StoreKitSubscriptionsViewController") SWIFT_AVAILABILITY(ios,introduced=17.0)
@interface StoreKitSubscriptionsViewController : UIViewController
@property (nonatomic, readonly, copy) NSString * _Nonnull subscriptionGroupIdentifier;
- (nonnull instancetype)initWithSubscriptionGroupIdentifier:(NSString * _Nonnull)subscriptionGroupIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class NSDate;
SWIFT_ENUM_FWD_DECL(NSInteger, StoreKitTransactionOwnershipType)
SWIFT_ENUM_FWD_DECL(NSInteger, StoreKitTransactionEnvironment)
SWIFT_ENUM_FWD_DECL(NSInteger, StoreKitTransactionReason)
SWIFT_ENUM_FWD_DECL(NSInteger, StoreKitTransactionRevocationReason)
@class StoreKitTransactionOffer;
SWIFT_ENUM_FWD_DECL(NSInteger, StoreKitTransactionVerificationStatus)
SWIFT_ENUM_FWD_DECL(NSInteger, StoreKitTransactionVerificationErrorCode)
SWIFT_CLASS("_TtC15StoreKitWrapper19StoreKitTransaction")
@interface StoreKitTransaction : NSObject
@property (nonatomic, readonly) uint64_t identifier;
@property (nonatomic, readonly) uint64_t originalIdentifier;
@property (nonatomic, readonly, copy) NSString * _Nullable webOrderLineItemIdentifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull appBundleIdentifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull productIdentifier;
@property (nonatomic, readonly) enum StoreKitProductType productType;
@property (nonatomic, readonly, copy) NSString * _Nullable subscriptionGroupIdentifier;
@property (nonatomic, readonly, copy) NSDate * _Nonnull purchaseDate;
@property (nonatomic, readonly, copy) NSDate * _Nonnull originalPurchaseDate;
@property (nonatomic, readonly, copy) NSDate * _Nullable expirationDate;
@property (nonatomic, readonly, copy) NSDate * _Nonnull signedDate;
@property (nonatomic, readonly, strong) NSDecimalNumber * _Nullable price;
@property (nonatomic, readonly, copy) NSString * _Nullable currencyCode;
@property (nonatomic, readonly) NSInteger purchasedQuantity;
@property (nonatomic, readonly) BOOL isUpgraded;
@property (nonatomic, readonly) enum StoreKitTransactionOwnershipType ownershipType;
@property (nonatomic, readonly) enum StoreKitTransactionEnvironment environment;
@property (nonatomic, readonly, copy) NSString * _Nullable storefrontIdentifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull storefrontCountryCode;
@property (nonatomic, readonly) enum StoreKitTransactionReason reason;
@property (nonatomic, readonly, copy) NSDate * _Nullable revocationDate;
@property (nonatomic, readonly) enum StoreKitTransactionRevocationReason revocationReason;
@property (nonatomic, readonly, copy) NSString * _Nullable appAccountToken;
@property (nonatomic, readonly, strong) StoreKitTransactionOffer * _Nullable offer;
@property (nonatomic, readonly, copy) NSString * _Nonnull jsonRepresentation;
@property (nonatomic, readonly, copy) NSString * _Nonnull jwsRepresentation;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceVerification;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceVerificationNonce;
@property (nonatomic, readonly) enum StoreKitTransactionVerificationStatus verificationStatus;
@property (nonatomic, readonly) enum StoreKitTransactionVerificationErrorCode verificationErrorCode;
@property (nonatomic, readonly, copy) NSString * _Nullable verificationErrorMessage;
- (nonnull instancetype)initWithIdentifier:(uint64_t)identifier originalIdentifier:(uint64_t)originalIdentifier webOrderLineItemIdentifier:(NSString * _Nullable)webOrderLineItemIdentifier appBundleIdentifier:(NSString * _Nonnull)appBundleIdentifier productIdentifier:(NSString * _Nonnull)productIdentifier productType:(enum StoreKitProductType)productType subscriptionGroupIdentifier:(NSString * _Nullable)subscriptionGroupIdentifier purchaseDate:(NSDate * _Nonnull)purchaseDate originalPurchaseDate:(NSDate * _Nonnull)originalPurchaseDate expirationDate:(NSDate * _Nullable)expirationDate signedDate:(NSDate * _Nonnull)signedDate price:(NSDecimalNumber * _Nullable)price currencyCode:(NSString * _Nullable)currencyCode purchasedQuantity:(NSInteger)purchasedQuantity isUpgraded:(BOOL)isUpgraded ownershipType:(enum StoreKitTransactionOwnershipType)ownershipType environment:(enum StoreKitTransactionEnvironment)environment storefrontIdentifier:(NSString * _Nullable)storefrontIdentifier storefrontCountryCode:(NSString * _Nonnull)storefrontCountryCode reason:(enum StoreKitTransactionReason)reason revocationDate:(NSDate * _Nullable)revocationDate revocationReason:(enum StoreKitTransactionRevocationReason)revocationReason appAccountToken:(NSString * _Nullable)appAccountToken offer:(StoreKitTransactionOffer * _Nullable)offer jsonRepresentation:(NSString * _Nonnull)jsonRepresentation jwsRepresentation:(NSString * _Nonnull)jwsRepresentation deviceVerification:(NSString * _Nonnull)deviceVerification deviceVerificationNonce:(NSString * _Nonnull)deviceVerificationNonce verificationStatus:(enum StoreKitTransactionVerificationStatus)verificationStatus verificationErrorCode:(enum StoreKitTransactionVerificationErrorCode)verificationErrorCode verificationErrorMessage:(NSString * _Nullable)verificationErrorMessage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, StoreKitTransactionEnvironment, open) {
  StoreKitTransactionEnvironmentUnknown = -1,
  StoreKitTransactionEnvironmentXcode = 0,
  StoreKitTransactionEnvironmentSandbox = 1,
  StoreKitTransactionEnvironmentProduction = 2,
};

SWIFT_ENUM_FWD_DECL(NSInteger, StoreKitTransactionOfferType)
SWIFT_ENUM_FWD_DECL(NSInteger, StoreKitTransactionOfferPaymentMode)
SWIFT_CLASS("_TtC15StoreKitWrapper24StoreKitTransactionOffer")
@interface StoreKitTransactionOffer : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable identifier;
@property (nonatomic, readonly) enum StoreKitTransactionOfferType offerType;
@property (nonatomic, readonly) enum StoreKitTransactionOfferPaymentMode paymentMode;
@property (nonatomic, readonly, strong) StoreKitSubscriptionPeriod * _Nullable period;
- (nonnull instancetype)initWithIdentifier:(NSString * _Nullable)identifier offerType:(enum StoreKitTransactionOfferType)offerType paymentMode:(enum StoreKitTransactionOfferPaymentMode)paymentMode period:(StoreKitSubscriptionPeriod * _Nullable)period OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, StoreKitTransactionOfferPaymentMode, open) {
  StoreKitTransactionOfferPaymentModeUnknown = -1,
  StoreKitTransactionOfferPaymentModeFreeTrial = 0,
  StoreKitTransactionOfferPaymentModePayAsYouGo = 1,
  StoreKitTransactionOfferPaymentModePayUpFront = 2,
  StoreKitTransactionOfferPaymentModeOneTime = 3,
};

typedef SWIFT_ENUM(NSInteger, StoreKitTransactionOfferType, open) {
  StoreKitTransactionOfferTypeUnknown = -1,
  StoreKitTransactionOfferTypeIntroductory = 0,
  StoreKitTransactionOfferTypePromotional = 1,
  StoreKitTransactionOfferTypeCode = 2,
  StoreKitTransactionOfferTypeWinBack = 3,
};

typedef SWIFT_ENUM(NSInteger, StoreKitTransactionOwnershipType, open) {
  StoreKitTransactionOwnershipTypeUnknown = -1,
  StoreKitTransactionOwnershipTypePurchased = 0,
  StoreKitTransactionOwnershipTypeFamilyShared = 1,
};

typedef SWIFT_ENUM(NSInteger, StoreKitTransactionReason, open) {
  StoreKitTransactionReasonUnknown = -1,
  StoreKitTransactionReasonPurchase = 0,
  StoreKitTransactionReasonRenewal = 1,
};

typedef SWIFT_ENUM(NSInteger, StoreKitTransactionRevocationReason, open) {
  StoreKitTransactionRevocationReasonNone = -1,
  StoreKitTransactionRevocationReasonDeveloperIssue = 0,
  StoreKitTransactionRevocationReasonOther = 1,
  StoreKitTransactionRevocationReasonUnknown = 999,
};

typedef SWIFT_ENUM(NSInteger, StoreKitTransactionVerificationErrorCode, open) {
  StoreKitTransactionVerificationErrorCodeNone = 0,
  StoreKitTransactionVerificationErrorCodeInvalidCertificateChain = 1,
  StoreKitTransactionVerificationErrorCodeInvalidDeviceVerification = 2,
  StoreKitTransactionVerificationErrorCodeInvalidEncoding = 3,
  StoreKitTransactionVerificationErrorCodeInvalidSignature = 4,
  StoreKitTransactionVerificationErrorCodeMissingRequiredProperties = 5,
  StoreKitTransactionVerificationErrorCodeRevokedCertificate = 6,
  StoreKitTransactionVerificationErrorCodeUnknown = 999,
};

typedef SWIFT_ENUM(NSInteger, StoreKitTransactionVerificationStatus, open) {
  StoreKitTransactionVerificationStatusUnverified = 0,
  StoreKitTransactionVerificationStatusVerified = 1,
};

typedef SWIFT_ENUM(NSInteger, StoreKitWrapperErrorCode, open) {
  StoreKitWrapperErrorCodeNone = 0,
  StoreKitWrapperErrorCodeUnknown = 1,
  StoreKitWrapperErrorCodeInvalidArgument = 2,
  StoreKitWrapperErrorCodeOperationCancelled = 3,
  StoreKitWrapperErrorCodeManagerNotInitialized = 10,
  StoreKitWrapperErrorCodeManagerShutdown = 11,
  StoreKitWrapperErrorCodeStoreKitNetworkError = 20,
  StoreKitWrapperErrorCodeStoreKitSystemError = 21,
  StoreKitWrapperErrorCodeStoreKitNotAvailableInStorefront = 22,
  StoreKitWrapperErrorCodeStoreKitNotEntitled = 23,
  StoreKitWrapperErrorCodeStoreKitUnknown = 24,
  StoreKitWrapperErrorCodeStoreKitUnsupported = 25,
  StoreKitWrapperErrorCodeProductsRequestInProgress = 100,
  StoreKitWrapperErrorCodeProductsRequestFailed = 101,
  StoreKitWrapperErrorCodeProductNotFound = 200,
  StoreKitWrapperErrorCodePurchaseInProgress = 201,
  StoreKitWrapperErrorCodePurchaseFailed = 202,
  StoreKitWrapperErrorCodeTransactionVerificationFailed = 203,
  StoreKitWrapperErrorCodePurchaseProductUnavailable = 204,
  StoreKitWrapperErrorCodePurchaseNotAllowed = 205,
  StoreKitWrapperErrorCodePurchaseInvalidQuantity = 206,
  StoreKitWrapperErrorCodePurchaseInvalidOfferIdentifier = 207,
  StoreKitWrapperErrorCodePurchaseInvalidOfferPrice = 208,
  StoreKitWrapperErrorCodePurchaseInvalidOfferSignature = 209,
  StoreKitWrapperErrorCodePurchaseMissingOfferParameters = 210,
  StoreKitWrapperErrorCodePurchaseIneligibleForOffer = 211,
  StoreKitWrapperErrorCodePurchasePaymentMethodBindingConfigurationRequired = 212,
  StoreKitWrapperErrorCodeTransactionNotFound = 300,
  StoreKitWrapperErrorCodeTransactionFinishInProgress = 301,
  StoreKitWrapperErrorCodeCurrentEntitlementsRequestInProgress = 400,
  StoreKitWrapperErrorCodeAppStoreSyncInProgress = 500,
  StoreKitWrapperErrorCodeAppStoreSyncFailed = 501,
  StoreKitWrapperErrorCodeUnfinishedTransactionsRequestInProgress = 600,
};

typedef SWIFT_ENUM(NSInteger, StoreKitWrapperLogLevel, open) {
  StoreKitWrapperLogLevelTrace = 0,
  StoreKitWrapperLogLevelDebug = 1,
  StoreKitWrapperLogLevelInformation = 2,
  StoreKitWrapperLogLevelWarning = 3,
  StoreKitWrapperLogLevelError = 4,
  StoreKitWrapperLogLevelCritical = 5,
  StoreKitWrapperLogLevelNone = 6,
};

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
