//
//  StoreKitTransactionTypes.swift
//  StoreKitWrapper
//
//  Created by Alessandro Morvillo on 13/08/2026.
//

import Foundation

/// Indicates whether StoreKit cryptographically verified a transaction.
@objc public enum StoreKitTransactionVerificationStatus: Int {
    /// The transaction failed verification and must not grant content.
    case unverified = 0
    /// StoreKit successfully verified the transaction.
    case verified = 1
}

/// Identifies the reason a transaction failed StoreKit verification.
@objc public enum StoreKitTransactionVerificationErrorCode: Int {
    /// No verification error occurred.
    case none = 0
    /// The certificate chain used to sign the transaction is invalid.
    case invalidCertificateChain = 1
    /// Device verification data is invalid.
    case invalidDeviceVerification = 2
    /// The signed transaction data has an invalid encoding.
    case invalidEncoding = 3
    /// The transaction signature is invalid.
    case invalidSignature = 4
    /// Required signed transaction properties are missing.
    case missingRequiredProperties = 5
    /// A certificate in the signing chain has been revoked.
    case revokedCertificate = 6
    /// The verification failure isn't recognized by this version of the wrapper.
    case unknown = 999
}

/// Describes how the current customer obtained a transaction.
@objc public enum StoreKitTransactionOwnershipType: Int {
    /// An ownership type that isn't recognized by this version of the wrapper.
    case unknown = -1
    /// The customer purchased the product directly.
    case purchased = 0
    /// The customer received access through Family Sharing.
    case familyShared = 1
}

/// Identifies the App Store environment that created a transaction.
@objc public enum StoreKitTransactionEnvironment: Int {
    /// An environment that isn't recognized by this version of the wrapper.
    case unknown = -1
    /// The transaction was generated by an Xcode StoreKit configuration.
    case xcode = 0
    /// The transaction was generated by the App Store sandbox.
    case sandbox = 1
    /// The transaction was generated by the production App Store.
    case production = 2
}

/// Describes why the App Store created a transaction.
@objc public enum StoreKitTransactionReason: Int {
    /// A reason that isn't recognized by this version of the wrapper.
    case unknown = -1
    /// The customer initiated a purchase.
    case purchase = 0
    /// StoreKit renewed an auto-renewable subscription.
    case renewal = 1
}

/// Identifies why the App Store revoked a transaction.
@objc public enum StoreKitTransactionRevocationReason: Int {
    /// The transaction hasn't been revoked.
    case none = -1
    /// The App Store refunded the transaction because of a developer issue.
    case developerIssue = 0
    /// The transaction was revoked for another recognized App Store reason.
    case other = 1
    /// The revocation reason isn't recognized by this version of the wrapper.
    case unknown = 999
}

/// Identifies the subscription offer applied to a transaction.
@objc public enum StoreKitTransactionOfferType: Int {
    /// An offer type that isn't recognized or no offer was reported.
    case unknown = -1
    /// An introductory offer was applied.
    case introductory = 0
    /// A promotional offer was applied.
    case promotional = 1
    /// An offer code was applied.
    case code = 2
    /// A win-back offer was applied.
    case winBack = 3
}

/// Describes how the offer attached to a transaction was charged.
@objc public enum StoreKitTransactionOfferPaymentMode: Int {
    /// A payment mode that isn't recognized or wasn't reported.
    case unknown = -1
    /// The offer provided a free trial.
    case freeTrial = 0
    /// The offer charged in installments.
    case payAsYouGo = 1
    /// The offer charged once for the full offer period.
    case payUpFront = 2
    /// The offer used a one-time payment.
    case oneTime = 3
}
